<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Cruzeiro', 'description' => 'El Cruzeiro Esporte Clube es un club de fútbol de la ciudad brasileña de Belo Horizonte, capital del Estado de Minas Gerais. Fue fundado el 2 de enero de 1921 y juega en el Campeonato Brasileño de Serie A. Fue considerado el mejor equipo brasileño del siglo XX según la IFFHS. Su clásico rival es el Clube Atlético Mineiro, con el que protagoniza el Clásico Mineiro. El Cruzeiro tiene la hinchada más grande del Estado de Minas Gerais, y una de las mayores de Brasil.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Logo_Cruzeiro_2016.png/128px-Logo_Cruzeiro_2016.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'River Plate', 'description' => 'El Club Atlético River Plate (en forma abreviada: River Plate o River) es una entidad deportiva de Argentina con sede en el barrio de Núñez, Buenos Aires. Su disciplina principal es el fútbol masculino profesional, que milita actualmente de la Primera División de Argentina, de la que es el club que registra la mayor cantidad de temporadas disputadas en toda la historia de la competición, así como es el club con mayor cantidad de partidos disputados y ganados, puntos logrados y goles convertidos, además de ser el club con la mayor cantidad de títulos. Asimismo, en el club se practican 65 disciplinas distintas,​ así como también ofrece institutos educativos de excelencia en todos los niveles académicos, y actividades culturales y sociales de diversa índole.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/RIVERNORMAL.png/128px-RIVERNORMAL.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Cerro Porteño', 'description' => 'El Club Cerro Porteño es una entidad deportiva con sede en el Barrio Obrero de la ciudad de Asunción, capital del Paraguay. Fue fundado el 1 de octubre de 1912 como Cerro Porteño Football Club. Los colores con los cuales se identifica son el rojo y el azul, que representan el signo de unión entre los paraguayos, simbolizado por los distintivos de los dos partidos políticos tradicionales del país, Colorado (rojo) y Liberal (azul). Es considerado por la FIFA como uno de los clubes «clásicos» del mundo.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Escudo_del_Club_Cerro_Porte%C3%B1o.png/200px-Escudo_del_Club_Cerro_Porte%C3%B1o.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'San Lorenzo', 'description' => 'El Club Atlético San Lorenzo de Almagro, conocido popularmente como San Lorenzo de Almagro o simplemente San Lorenzo es un club deportivo, social y cultural de Argentina, fue fundado el 1 de abril de 1908. Su principal actividad es el fútbol. Practica también el básquet (del cual es uno de los clubes más ganadores), natación, atletismo, hockey, rugby y vóley entre otras disciplinas deportivas. Es un club que se destaca por haber sido multicampeón en todos los deportes, teniendo en su haber campeones olímpicos como Delfo Cabrera. Está incorporado al sistema educativo con un jardín de infantes y un próximo colegio secundario.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Escudo-San-Lorenzo.png/141px-Escudo-San-Lorenzo.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Olimpia', 'description' => 'El Club Olimpia es una entidad deportiva con sede en la ciudad de Asunción, Paraguay. Promueve la práctica de varios deportes. Fue fundado el 25 de julio de 1902 por un grupo de jóvenes paraguayos. ​El nombre nace a raíz de la idea de su miembro fundador principal, William Paats, un holandés radicado en Paraguay a fines del siglo XIX, quien es considerado el padre del fútbol paraguayo por haber insertado y fomentado la práctica de dicha disciplina deportiva en el país. El equipo de fútbol ejerce sus partidos de local en el Estadio Tigo Manuel Ferreira, más conocido como "El Bosque de Para Uno".', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Emblem_Olimpia.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Liga de Quito', 'description' => 'Liga Deportiva Universitaria, conocido también como Liga de Quito o simplemente Liga y por sus siglas LDU, es un club deportivo ecuatoriano originario de la ciudad de Quito. Fue fundado el 11 de enero de 1930, aunque sus actividades iniciaron en 1918 como un equipo de fútbol universitario de la Universidad Central del Ecuador llamado Club Universitario.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Liga_Deportiva_Universitaria_de_Quito.png/200px-Liga_Deportiva_Universitaria_de_Quito.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Boca Juniors', 'description' => 'El Club Atlético Boca Juniors (en forma abreviada: Boca Juniors o Boca) es una entidad deportiva de Argentina con sede en el barrio de La Boca, Buenos Aires. El fútbol es su disciplina más destacada, aunque también compite a nivel profesional, nacional e internacionalmente, en baloncesto, voleibol, futsal y fútbol femenino, mientras que deportes como el boxeo, judo, karate, taekwondo, lucha, gimnasia rítmica y artística se practican a nivel amateur.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Boca_Juniors_2012.svg/138px-Boca_Juniors_2012.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Athletico Paranaense', 'description' => 'El Clube Athletico Paranaense es un equipo de fútbol brasileño de la ciudad de Curitiba, en el estado de Brasil. Fue fundado el 26 de marzo de 1924 de la fusión del Internacional Football Club y el América Paraná. Su estadio es el Arena da Baixada. Es popularmente conocido como Furacão (Huracán), apodo que se ganó en la década del 50. Entre sus títulos más destacados figuran la Copa Sudamericana 2018, el Brasileirao 2001, 24 títulos del Campeonato Paranaense y ser subcampeón de la Copa Libertadores 2005. Además se convirtió en el primer equipo de Paraná en participar en una competencia nacional e internacional.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/CA_Paranaense.svg/160px-CA_Paranaense.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Palmeiras', 'description' => 'La Sociedade Esportiva Palmeiras (en español: Sociedad Deportiva Palmeras) es un club de fútbol brasileño de la ciudad de São Paulo. Conocido popularmente de forma abreviada como Palmeiras o "verdão" o "alviverde", fue fundado el 26 de agosto de 1914, como Palestra Italia, pero su nombre fue cambiado al actual el 14 de septiembre de 1942 por razones políticas.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Palmeiras_logo.svg/160px-Palmeiras_logo.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Godoy Cruz', 'description' => 'El Club Deportivo Godoy Cruz Antonio Tomba, denominado «Tomba» o simplemente «Godoy Cruz», es una institución deportiva de la ciudad homónima del Gran Mendoza, provincia de Mendoza, Argentina. Fue fundado el 1 de junio de 1921 con el nombre de Club Sportivo Godoy Cruz, aunque adoptó su actual nombre el 26 de septiembre de 1930, luego de fusionarse con el Club Bodega Antonio Tomba, entidad que fue fundada en 1899 por los obreros de la histórica bodega con el auspicio de Don Antonio Tomba.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/GCAT.png/156px-GCAT.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Libertad', 'description' => 'El Club Libertad es una entidad deportiva con sede en el barrio Las Mercedes, más conocido como Tuyucuá (Tujukua) de la ciudad de Asunción, capital del Paraguay. Fue fundado el 30 de julio de 1905.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Club_Libertad.png/200px-Club_Libertad.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Gremio', 'description' => 'El Grêmio Foot-Ball Porto Alegrense (conocido simplemente como Grêmio) es un club de fútbol brasileño, de la ciudad de Porto Alegre en el estado de Río Grande del Sur. Fue fundado por inmigrantes ingleses y alemanes el 15 de septiembre de 1903 y juega en el Campeonato Brasileño de Serie A. Disputa sus partidos de local en el Arena do Grêmio. Es considerado, según la confederación brasileña de fútbol, el principal club del actual fútbol brasileño.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Gremio-Logo.png/180px-Gremio-Logo.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Flamengo', 'description' => 'El Clube de Regatas do Flamengo, conocido simplemente como Flamengo, es un club deportivo de la ciudad de Río de Janeiro, Brasil, conocido fundamentalmente por su sección de fútbol. Fundado el 15 de noviembre de 1895, juega de local en el Estadio Maracaná y utiliza una camiseta roja y negra a franjas horizontales con pantalón blanco. Flamengo es uno de los cuatro clubes brasileños que nunca ha descendido de la Primera División de Brasil, siendo los otros: Cruzeiro, Santos FC y São Paulo.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flamengo_braz_logo.svg/133px-Flamengo_braz_logo.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Emelec', 'description' => 'Club Sport Emelec, mayormente conocido como Emelec, es un club deportivo ecuatoriano originario de la ciudad de Guayaquil, fundado el 28 de abril de 1929 por el estadounidense George Capwell.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Club-Sport-Emelec.png/160px-Club-Sport-Emelec.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Internacional', 'description' => 'El Sport Club Internacional, conocido popularmente como Inter de Porto Alegre y a veces referenciado en Brasil como Inter-RS (Rio Grande do Sul)​, es un club de fútbol de la ciudad de Porto Alegre, capital del estado de Rio Grande do Sul, fue fundado el 4 de abril de 1909. Actualmente se desempeña en el Campeonato Brasileño de Serie A. Su clásico rival es Grêmio FBPA también de la ciudad de Porto Alegre, con el cual disputa el Grenal o Clásico Gaúcho, mayor y mas importante rivalidad deportiva entre equipos de fútbol del estado de Rio Grande do Sul.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Escudo_do_Sport_Club_Internacional.svg/175px-Escudo_do_Sport_Club_Internacional.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '1', 'name' => 'Nacional', 'description' => 'El Club Nacional de Football es una institución deportiva de Uruguay, fundada el 14 de mayo de 1899 en Montevideo, tras la fusión, por iniciativa de jóvenes estudiantes de la época, de los clubes Uruguay Athletic, cuya sede era en La Unión, y Montevideo Football Club, con la intención de crear y consolidar una institución de fútbol para uruguayos criollos frente al predominio de clubes y practicantes de extranjeros europeos de este deporte, particularmente ingleses, siendo considerado así el "primer equipo criollo" de Uruguay y uno de los primeros clubes fundados por nacionales en América.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Escudo_nacional.svg/155px-Escudo_nacional.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Royal Pari', 'description' => 'Royal Pari, más conocido simplemente como Royal Pari, es un club de fútbol radicado en la ciudad de Santa Cruz de la Sierra, Bolivia. Fue fundado en 1993 y desde la temporada 2018 participa en la Primera División de Bolivia y la temporada 2019 participará en la Copa Sudamericana siendo su primera participación a nivel internacional.', 'icon' => 'https://www.mismarcadores.com/res/image/data/IFErB3HG-AetXWB0b.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'La Equidad', 'description' => 'El Club Deportivo La Equidad, cuya razón social es Club Deportivo La Equidad Seguros Sociedad Anónima, también conocido simplemente como La Equidad es un club de fútbol de la ciudad de Bogotá, Colombia.', 'icon' => 'https://www.mismarcadores.com/res/image/data/jRH9PPzB-GArubhDE.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Botafogo', 'description' => 'El Botafogo de Futebol e Regatas es un club deportivo brasileño con sede en el barrio homónimo, en Río de Janeiro. Sus mayores glorias deportivas son principalmente en el fútbol, pero también se destaca en el remo, voleibol, baloncesto, deportes acuáticos y otros más. Fundado en remo el 1 de julio de 1894 con el nombre de Club de Regatas Botafogo, se fusionó con el Botafogo Football Club el 8 de diciembre de 1942 (el día de homenaje al club de la patrona, Nuestra Señora de la Concepción), otro club del mismo barrio, fundado oficialmente el 12 de agosto de 1904. Sus colores son negro y blanco y sus seguidores se llaman botafoguenses. Botafogo es un equipo muy conocido porque tiene el mayor número de jugadores llamados a la selección brasileña: son 97 en general y 47 en Copas del Mundo.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Botafogo_de_Futebol_e_Regatas_logo.svg/142px-Botafogo_de_Futebol_e_Regatas_logo.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Atlético Mineiro', 'description' => 'El Clube Atlético Mineiro (o simplemente Atlético y cuyo acrónimo es CAM) es un club multi-deportivo con sede en Belo Horizonte, capital del Estado de Minas Gerais, Brasil. Fundado en 25 de marzo de 1908 por un grupo de estudiantes, tiene como sus tradicionales colores el blanco y negro. Su símbolo y más popular apodo es el Galo (gallo), mascota oficial a finales del 1930. De acuerdo con BDO RCS Auditores Independientes, la marca de Atlético es el noveno valor más alto entre los clubes de Brasil, superando los 357 millones de reales.​ Según la encuesta de IBOPE llevado a cabo en 2014, el Atlético es oficialmente el club fuera del eje Río de Janeiro-São Paulo más popular de Brasil.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Atletico_mineiro_galo.png/105px-Atletico_mineiro_galo.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Zulia' , 'description' => 'Zulia Fútbol Club es un club de fútbol con sede en la ciudad de Maracaibo, capital del estado Zulia. Los colores que identifican al club son los mismos de la bandera del estado Zulia: el azul predominante y el negro. El club se fundó el 30 de junio de 2005 y empezó a jugar en la Segunda División B de Venezuela en la temporada 2006/07, ascenderían a la Segunda División de Venezuela en la temporada 2007/2008 y finalmente, subieron a la máxima liga del balompié venezolano en la temporada 2008-09 consiguiendo un impensado 5to lugar en el certamen.', 'icon' => 'https://www.mismarcadores.com/res/image/data/8K9KIZAr-beXpWQwB.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Sporting Cristal', 'description' => 'El Club Sporting Cristal S.A. es una institución deportiva peruana, ubicada en la ciudad de Lima y cuya principal actividad es el fútbol. Fue fundado el 13 de diciembre de 1955 en el distrito del Rímac por el ingeniero Ricardo Bentín Mujica y su esposa Esther Grande de Bentín, propietarios de la cervecería peruana Backus & Johnston.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Escudo_del_Club_Sporting_Cristal.svg/98px-Escudo_del_Club_Sporting_Cristal.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Colón', 'description' => 'El Club Atlético Colón, también conocido como Colón de Santa Fe o simplemente Colón, es un club deportivo de Argentina de la ciudad de Santa Fe. Fue fundado, el 5 de mayo de 1905 como el Colón Foot-Ball Club, hasta que en 1920 se adopta el nombre actual. Su principal equipo de fútbol participa en el campeonato de Primera División de Argentina.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Escudo_del_C._A._Col%C3%B3n.png/144px-Escudo_del_C._A._Col%C3%B3n.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Argentinos Juniors', 'description' => 'La Asociación Atlética Argentinos Juniors, popularmente conocida como Argentinos Juniors o simplemente Argentinos, es una centenaria institución polideportiva fundada el 15 de agosto de 1904 en el barrio de La Paternal, Ciudad Autónoma de Buenos Aires, Argentina. Juega actualmente en la Primera División.', 'icon' => 'https://www.mismarcadores.com/res/image/data/xplqslf5-IHcrNFsb.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Caracas Fútbol Club', 'description' => 'El Caracas Fútbol Club es un club de fútbol profesional con sede en la ciudad de Caracas, capital de Venezuela. Fundado el 12 de diciembre de 1967, por iniciativa de un grupo de aficionados, con la idea de tener un club de fútbol en el cual pudiesen distraerse en sus ratos libres. Pero no sería sino hasta el año 1984 que participaría en un torneo profesional, jugando la segunda división bajo el nombre de Caracas-Yamaha, consiguiendo ese mismo año el ascenso y pasando a denominarse Caracas Fútbol Club en el año 1985.', 'icon' => 'https://www.mismarcadores.com/res/image/data/hIuNHZFG-zT0R3GJn.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Independiente del Valle', 'description' => 'El Club Especializado de Alto Rendimiento Independiente del Valle, mayormente conocido como Independiente del Valle, es un club deportivo ecuatoriano originario de la ciudad de Sangolquí. Fue fundado el 1 de marzo de 1958 con el nombre de Club Social y Deportivo Independiente José Terán.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Escudo_IDV.png/133px-Escudo_IDV.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Independiente', 'description' => 'El Club Atlético Independiente, conocido popularmente como Independiente o por su sigla CAI, es una entidad deportiva de Argentina con sede en la ciudad bonaerense de Avellaneda, situado en el sur del Gran Buenos Aires (GBA). Fue fundado el 1 de enero de 1905 por unos jóvenes empleados independistas del Club Maipú. El fútbol es su disciplina más destacada, cuyo primer equipo participa anualmente de la Primera División de Argentina, aunque también se practican otras disciplinas deportivas a nivel amateur y semiprofesional.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Escudo_del_Club_Atl%C3%A9tico_Independiente.svg/154px-Escudo_del_Club_Atl%C3%A9tico_Independiente.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Universidad Católica (Ecuador)', 'description' => 'Club Deportivo de la Universidad Católica, mayormente conocido como Universidad Católica, es un club deportivo ecuatoriano originario de la ciudad de Quito, fundado el 15 de mayo de 1963.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Escudo_Universidad_Catolica.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Peñarol', 'description' => 'El Club Atlético Peñarol es una institución deportiva de Montevideo, Uruguay. Toma su nombre del barrio Peñarol, ubicado en noreste de la ciudad.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Escudo_del_Club_Atl%C3%A9tico_Pe%C3%B1arol.svg/119px-Escudo_del_Club_Atl%C3%A9tico_Pe%C3%B1arol.svg.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Fluminense', 'description' => 'El Fluminense Football Club (conocido simplemente como Fluminense) es un club polideportivo brasileño con sede en la ciudad de Río de Janeiro. Fue fundado el 21 de julio de 1902 en Río de Janeiro por Oscar Cox, un brasileño de origen británico. El acto fundacional se llevó a cabo en el caserón residencial de Horácio da Costa Santos, ubicado en la calle Rua Marquês de Abrantes, número 51.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Fluminense_FC_escudo.png/180px-Fluminense_FC_escudo.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Corinthians', 'description' => 'El Sport Club Corinthians Paulista, conocido simplemente como Corinthians, es un club polideportivo con sede en la ciudad de São Paulo, Brasil. Si bien la institución participa en numerosos deportes, su reconocimiento y sus principales logros se han conseguido en el fútbol masculino profesional. A 2018, compite en Campeonato Brasileño de Serie A y en el Campeonato Paulista.', 'icon' => 'https://www.mismarcadores.com/res/image/data/lY91WW9r-AkqTkErP.png']);
        DB::table('teams')->insert(['bracket_id' => '11', 'name' => 'Montevideo Wanderers', 'description' => 'Montevideo Wanderers Fútbol Club, popularmente conocido simplemente como Wanderers, es un equipo de fútbol uruguayo con sede en Montevideo. Fue fundado en 1902 y actualmente milita en la Primera División Profesional de Uruguay. El club disputa sus partidos como local en el Parque Alfredo Víctor Viera, estadio con capacidad para 15 000 espectadores.', 'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Escudo_del_Montevideo_Wanderers_Futbol_Club.png/138px-Escudo_del_Montevideo_Wanderers_Futbol_Club.png']);
        
    }
}
